apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: generalscaler-binding
subjects:
- kind: ServiceAccount
  name: generalscaler-sa
  namespace: default     
roleRef:
  kind: ClusterRole
  name: generalscaler-controller
  apiGroup: rbac.authorization.k8s.io